# Константы путей к файлам / директориям
NO_IMAGE = 'noimage.png'
START_BACKGROUND = 'start_background.png'
START_BUTTON = 'start_button.png'
MAP_BACKGROUND = 'map_background.png'
SETTINGS_BUTTON = 'settings_button.png'
HOME_BUTTON = 'home_button.png'
ENCYCLOPEDIA_BUTTON = 'encyclopedia_button.png'
UPGRADING_BUTTON = 'upgrading_button.png'
COMPLETE_LEVEL = 'complete_level.png'
INCOMPLETE_LEVEL = 'incomplete_level.png'