# Здесь всякике служебные константы
START_MENU = 0
MAIN_MENU = 1
LEVEL_PLAY = 2
UPGRADING = 3
QUIT = -1
VELOCITY_BUFF = 1e2
DAMAGE_BUFF = 1e2 + 1
FLY_ABILITY = 1e2 + 2
ATTACK_SPEED_BUFF = 1e2 + 3
PAUSE = 4
DAMAGE = "damage"
HEALTH = "health"
VELOCITY = "velocity"
FLYING = "flying"
IMAGE_PATH = "image"
REWARD = "reward"
PRICE = "price"
ATTACK_SPEED = "speed"
TOWER_DAMAGE_BUFF = "damage_buff"
TOWER_VELOCITY_BUFF = "velocity_buff"
ATTACK_AIR = "air"
BULLET_IMAGE = "bullet_image"
BULLET_VELOCITY = "bullet_velocity"
ATTACK_RADIUS = "radius"
BULLET_TIME = "bullet_time"
TOWER_BUFFS_TIME = "buffs_time"
TOWER_ICON = "icon"
